name: Validate test suites
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get yamllint and wake-up the mirror endpoint
        run: |
          sudo apt-get install -y curl wget yamllint
          curl --connect-timeout 600 -sk https://oshp-validator-mock.onrender.com
      - name: Validate the Venom test suite file using custom configuation
        run: |
          yamllint --strict tests_suite.yml         
      - name: Get venom
        run: |
          wget -q -O venom https://github.com/ovh/venom/releases/download/v1.0.1/venom.linux-amd64
          chmod +x venom
          ./venom update || true
      - name: Execute the test plan
        run: |
          ./venom run --var="target_site=https://oshp-validator-mock.onrender.com" --var="internet_facing=true" --var="logout_url=/" tests_suite.yml

